"""Add dateCreation column

Revision ID: 11ca562a6721
Revises: e13925fd0572
Create Date: 2025-06-16 20:49:31.763959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ca562a6721'
down_revision: Union[str, None] = 'e13925fd0572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_favorite_jobs_id'), 'favorite_jobs', ['id'], unique=False)
    op.add_column('jobs', sa.Column('dateCreation', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'dateCreation')
    op.drop_index(op.f('ix_favorite_jobs_id'), table_name='favorite_jobs')
    # ### end Alembic commands ###
