"""Recreate jobs table with external_id

Revision ID: 4fadec73b3de
Revises: 19e0bd1af723
Create Date: 2025-08-27 11:07:31.888669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fadec73b3de'
down_revision: Union[str, None] = '19e0bd1af723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'applied_jobs', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'liked_jobs', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'seen_jobs', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seen_jobs', type_='foreignkey')
    op.drop_constraint(None, 'liked_jobs', type_='foreignkey')
    op.drop_constraint(None, 'applied_jobs', type_='foreignkey')
    # ### end Alembic commands ###
